CUDA_VISIBLE_DEVICES=7 python general_main.py \
    --data cifar100 \
    --seed 10086 \
    --cl_type nc \
    --agent GDUMB \
    --tag gdumb-1000 \
    --retrieve random \
    --update random \
    --mem_size 1000 \
    --images_per_class 10 \
    --head mlp \
    --temp 0.07 \
    --eps_mem_batch 100 \
    --num_runs 5 \